### ISSUE TITLE
Library is not thread-safe with MSVC 2013

### ISSUE THREAD

**Issue by Markus43** [MEONMedical/Log4Qt#11]
Since [this](https://github.com/MEONMedical/Log4Qt/commit/a40464b3da6dc43318a6ac6bdcdd6b63b01c8b1b#diff-c74a744b1f354584241badcd69cc7a37) commit Log4Qt heavily uses C++11's magic statics feature.

Since CI is testing the library with MSVC 2013, I was assuming that the C++11 features of this compiler are sufficient for using Log4Qt. However, this is not true: MSVC 2013 does not support "Magic statics", see [https://msdn.microsoft.com/en-us/library/hh567368%28v=vs.120%29.aspx](url) .

**Comment by andibacher** [comment]
Thank for your observation, the unit test propably do not cover the thread safty. We were not aware that msvc 2013 dies not support the feature  "Magic statics" which we used in some part for thread safty. I added the minimum required compiler in tne readme and removed the CI testing for MSVC 2013. We are not going to fix this for compiler not supporting the magic status features, because the goal of this fork is to provide a more modern implementation of the original log4t.
